rails/website/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :records
  resources :home

end

rails/website/app/models/record.rb
class Record < ActiveRecord::Base
end

rails/website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails/website/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

rails/website/app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:name, :money, :commodity)
    end
end

rails/website/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/website/app/helpers/records_helper.rb
module RecordsHelper
end

rails/website/app/views/home/index.html.erb
<h1>test</h1>
<div class="progress progress-striped active">
   <div class="progress-bar progress-bar-success" role="progressbar" 
      aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" 
      style="width: 40%;">
      <span>40% 完成</span>
   </div>
</div>

rails/website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- 新 Bootstrap 核心 CSS 文件 -->
	<link href="http://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">

	<!-- 可选的Bootstrap主题文件（一般不使用） -->
	<script src="http://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap-theme.min.css"></script>

	<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
	<script src="http://apps.bdimg.com/libs/jquery/2.0.0/jquery.min.js"></script>

	<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
	<script src="http://apps.bdimg.com/libs/bootstrap/3.3.0/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
    <% unless notice.nil? %>
    <div class="alert alert-info"><%= notice %></div>
    <% end %>
    <% unless alert.nil? %>
    <div class="alert alert-danger"><%= alert %></div>
    <% end %>
    <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

rails/website/app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :money %><br>
    <%= f.text_field :money %>
  </div>
  <div class="field">
    <%= f.label :commodity %><br>
    <%= f.text_field :commodity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/website/app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

rails/website/app/views/records/index.html.erb
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#">首页</a>
  </li>
  <li>
    <a href="#">资料</a>
  </li>
  <li class="disabled">
    <a href="#">信息</a>
  </li>
  <li class="dropdown pull-right">
    <a href="#" data-toggle="dropdown" class="dropdown-toggle">
      下拉 <strong class="caret"></strong>
    </a>
    <ul class="dropdown-menu">
      <li>
        <a href="#">操作</a>
      </li>
      <li>
        <a href="#">设置栏目</a>
      </li>
      <li>
        <a href="#">更多设置</a>
      </li>
      <li class="divider"></li>
      <li>
        <a href="#">分割线</a>
      </li>
    </ul>
  </li>
</ul>
<p id="notice"><%= notice %></p>
<div class="table-responsive">
  <h1>Listing Records</h1>
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Money</th>
        <th>Commodity</th>
        <th colspan="3">operating</th>
      </tr>
    </thead>

    <tbody>
      <% @records.each do |record| %>
        <tr>
          <td><%= record.name %></td>
          <td><%= record.money %></td>
          <td><%= record.commodity %></td>
          <td><%= link_to 'Show', record %></td>
          <td><%= link_to 'Edit', edit_record_path(record) %></td>
          <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= link_to 'New Record', new_record_path %>
</div>
<div class="progress progress-striped active">
   <div class="progress-bar progress-bar-success" role="progressbar" 
      aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" 
      style="width: 40%;">
      <span>40% 完成</span>
   </div>
</div>

rails/website/app/views/records/new.html.erb
<h1>New Record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

rails/website/app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @record.name %>
</p>

<p>
  <strong>Money:</strong>
  <%= @record.money %>
</p>

<p>
  <strong>Commodity:</strong>
  <%= @record.commodity %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>